# Generated by Django 4.2 on 2025-01-13 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labelcolors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearRegistroMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioLey', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etiqueta1', models.CharField(blank=True, max_length=255, null=True)),
                ('etiqueta2', models.CharField(blank=True, max_length=255, null=True)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('cilindraje', models.PositiveIntegerField(blank=True, null=True)),
                ('modelo', models.PositiveIntegerField(blank=True, null=True)),
                ('chasis', models.CharField(max_length=17)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('nombreCompleto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tiempoTramite', models.CharField(blank=True, max_length=255, null=True)),
                ('cuentaBancaria', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_movilidad', to='labelcolors.labelcolor')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_movilidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubregistrosMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=50)),
                ('campo_modificado', models.CharField(max_length=255)),
                ('valor_antes', models.TextField(blank=True, null=True)),
                ('valor_despues', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subregistros_movilidad', to='labelcolors.labelcolor')),
                ('idregistroMovilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregistros', to='teammovilidad.crearregistromovilidad')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subregistros_movilidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
