# Generated by Django 4.2 on 2025-01-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammovilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearregistromovilidad',
            name='comision',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crearregistromovilidad',
            name='precioLey',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='crearregistromovilidad',
            name='total',
            field=models.CharField(max_length=255),
        ),
    ]
