# Generated by Django 4.2 on 2025-01-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammovilidad', '0002_alter_crearregistromovilidad_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearregistromovilidad',
            name='comision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crearregistromovilidad',
            name='precioLey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='crearregistromovilidad',
            name='total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
