# Generated by Django 4.2 on 2025-01-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammovilidad', '0004_rename_cedula_crearregistromovilidad_numerodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearregistromovilidad',
            name='cilindraje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crearregistromovilidad',
            name='modelo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
