# Generated by Django 4.2 on 2025-01-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammovilidad', '0005_alter_crearregistromovilidad_cilindraje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearregistromovilidad',
            name='linkpago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crearregistromovilidad',
            name='pagoinmediato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crearregistromovilidad',
            name='tipocomision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
